name: Feature request
description: Suggest an improvement
title: '[Feature]: '
labels: ['enhancement']
body:
  - type: textarea
    attributes:
      label: What problem does this solve?
      description: Describe the pain point you’re experiencing.
    validations:
      required: true

  - type: textarea
    attributes:
      label: What would you like to see?
      description: Describe the solution you’re proposing.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: Links, screenshots, or anything else helpful.
